# Lamp control logic
- alias: Lamp on period
  trigger:
    - platform: time
      after: '20:23:00'
  condition:
    - condition: state
      entity_id: input_boolean.override
      state: 'off'
  action: 
    - service: shell_command.set_lamp_on
    - service: input_boolean.turn_on
      entity_id: input_boolean.lamp_value

- alias: Lamp off period
  trigger:
    - platform: time
      after: '20:23:05'
  condition:
    - condition: state
      entity_id: input_boolean.override
      state: 'off'
  action: 
    - service: shell_command.set_lamp_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.lamp_value

# Lamp override
- alias: Lamp on override
  trigger:
    platform: state
    entity_id: input_boolean.lamp_control
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.override
      state: 'on'
  action: 
    - service: shell_command.set_lamp_on
    - service: input_boolean.turn_on
      entity_id: input_boolean.lamp_value

- alias: Lamp off override
  trigger:
    platform: state
    entity_id: input_boolean.lamp_control
    from: 'on'
    to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.override
      state: 'on'
  action: 
    - service: shell_command.set_lamp_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.lamp_value

# Fan control logic
- alias: Start fan by temperature
  trigger:
    platform: numeric_state
    entity_id: sensor.temperature
    above: 40
  condition:
    - condition: state
      entity_id: input_boolean.override
      state: 'off'
  action: 
    - service: shell_command.set_fan_on
    - service: input_boolean.turn_on
      entity_id: input_boolean.fan_value

- alias: Start fan by humidity
  trigger:
    platform: numeric_state
    entity_id: sensor.humidity
    above: 40
  condition:
    - condition: state
      entity_id: input_boolean.override
      state: 'off'
  action: 
    - service: shell_command.set_fan_on
    - service: input_boolean.turn_on
      entity_id: input_boolean.fan_value

- alias: Stop fan by temperature
  trigger:
    platform: numeric_state
    entity_id: sensor.temperature
    below: 35
  condition:
    - condition: state
      entity_id: input_boolean.override
      state: 'off'
  action: 
    - service: shell_command.set_fan_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.fan_value

- alias: Stop fan by humidity
  trigger:
    platform: numeric_state
    entity_id: sensor.humidity
    below: 35
  condition:
    - condition: state
      entity_id: input_boolean.override
      state: 'off'
  action: 
    - service: shell_command.set_fan_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.fan_value

# Fan override
- alias: Fan on override
  trigger:
    platform: state
    entity_id: input_boolean.fan_control
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.override
      state: 'on'
  action: 
    - service: shell_command.set_fan_on
    - service: input_boolean.turn_on
      entity_id: input_boolean.fan_value

- alias: Fan off override
  trigger:
    platform: state
    entity_id: input_boolean.fan_control
    from: 'on'
    to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.override
      state: 'on'
  action: 
    - service: shell_command.set_fan_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.fan_value

