homeassistant:
    # Name of the location where Home Assistant is running
    name: Home
    # C for Celcius, F for Fahrenheit
    unit_system: metric

    # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    time_zone: Europe/Prague

    customize:
        input_boolean.fan_value:
            hidden: true
        input_boolean.lamp_value:
            hidden: true
        binary_sensor.trigger_on_temperature:
            hidden: true
        binary_sensor.trigger_off_temperature:
            hidden: true
        binary_sensor.trigger_on_humidity:
            hidden: true
        binary_sensor.trigger_off_humidity:
            hidden: true

# Enables the frontend
frontend:

# Checks for available updates
updater:

# View all events in a logbook
logbook:

# Allows you to issue voice commands from the frontend
conversation:
# Enables support for tracking state changes over time.
history:
# Discover some devices automatically
discovery:

# Show links to resources in log and frontend
# introduction:
http:
  api_password: hovno



#################################################################

## Components

#################################################################
input_boolean:
    override:
        name: Override all automation
        initial: off
        icon: mdi:car

    fan_control:
        name: Fan control
        initial: off
        icon: mdi:fan

    fan_value:
        name: Fan value
        initial: off
        icon: mdi:fan

    lamp_control:
        name: Lamp control
        initial: off
        icon: mdi:lightbulb-outline

    lamp_value:
        name: Lamp value
        initial: off
        icon: mdi:lightbulb-outline

sensor:
    - platform: command_line
      name: Temperature
      command: cat ~/hass/temp/temperature
      unit_of_measurement: "째C"
      value_template: '{{ value }}'

    - platform: command_line
      name: Humidity
      command: cat ~/hass/temp/humidity
      unit_of_measurement: "%"
      value_template: '{{ value }}'

    - platform: time_date
      display_options:
        - 'time'

    - platform: template
      sensors:
        time_lamp_on:
            friendly_name: Lamp time ON
            value_template: "{% if states.input_slider.time_lamp_on_hour.state | int < 10 %}0{% endif %}{{ states.input_slider.time_lamp_on_hour.state | int }}:{% if states.input_slider.time_lamp_on_minute.state | int < 10 %}0{% endif %}{{ states.input_slider.time_lamp_on_minute.state | int }}"
        time_lamp_off:
            friendly_name: Lamp time OFF
            value_template: "{% if states.input_slider.time_lamp_off_hour.state | int < 10 %}0{% endif %}{{ states.input_slider.time_lamp_off_hour.state | int }}:{% if states.input_slider.time_lamp_off_minute.state | int < 10 %}0{% endif %}{{ states.input_slider.time_lamp_off_minute.state | int }}"
        temperature_fan_threshold_value:
            friendly_name: Temperature threshold
            value_template: "{{ states.input_slider.temperature_fan_threshold.state | int }} (+-{{ states.input_slider.temperature_fan_hysteresis.state | int }}) 째C"
        humidity_fan_threshold_value:
            friendly_name: Humidity threshold
            value_template: "{{ states.input_slider.humidity_fan_threshold.state | int }} (+-{{ states.input_slider.humidity_fan_hysteresis.state | int }}) %"

binary_sensor: 
    - platform: template 
      sensors:
        fan:
            friendly_name: Fan
            value_template: "{{ states.input_boolean.fan_value.state == 'on' }}"
            sensor_class: opening
        lamp:
            friendly_name: Lamp
            value_template: "{{ states.input_boolean.lamp_value.state == 'on' }}" 
            sensor_class: light
        trigger_on_temperature:
            friendly_name: TrigOnTemp
            value_template: "{{ float(states.sensor.temperature.state) > (float(states.input_slider.temperature_fan_threshold.state) + float(states.input_slider.temperature_fan_hysteresis.state)) }}"
        #TODO Change condition to '<'
        trigger_off_temperature:
            friendly_name: TrigOffTemp
            value_template: "{{ float(states.sensor.temperature.state) > (float(states.input_slider.temperature_fan_threshold.state) - float(states.input_slider.temperature_fan_hysteresis.state)) }}"
        trigger_on_humidity:
            friendly_name: TrigOnHum
            value_template: "{{ float(states.sensor.humidity.state) > (float(states.input_slider.humidity_fan_threshold.state) + float(states.input_slider.humidity_fan_hysteresis.state)) }}"
        #TODO Change condition to '<'
        trigger_off_humidity:
            friendly_name: TrigOffHum
            value_template: "{{ float(states.sensor.humidity.state) > (float(states.input_slider.humidity_fan_threshold.state) - float(states.input_slider.humidity_fan_hysteresis.state)) }}"

input_slider:
  temperature_fan_threshold:
    name: Temperature threshold(째C)
    initial: 40
    min: 20
    max: 50
    step: 1
    icon: mdi:fan
  humidity_fan_threshold:
    name: Humidity threshold(%)
    initial: 40
    min: 0
    max: 100
    step: 1
    icon: mdi:fan
  temperature_fan_hysteresis:
    name: Temperature hysteresis(째C)
    initial: 1
    min: 0
    max: 5
    step: 1
    icon: mdi:fan
  humidity_fan_hysteresis:
    name: Humidity hysteresis(%)
    initial: 1
    min: 0
    max: 5
    step: 1
    icon: mdi:fan
  time_lamp_on_hour:
    name: Lamp ON(hour)
    initial: 12
    min: 0
    max: 23
    step: 1
    icon: mdi:clock
  time_lamp_on_minute:
    name: Lamp ON(min)
    initial: 1
    min: 0
    max: 59
    step: 1
    icon: mdi:clock
  time_lamp_off_hour:
    name: Lamp OFF(hour)
    initial: 12
    min: 0
    max: 23
    step: 1
    icon: mdi:clock
  time_lamp_off_minute:
    name: Lamp OFF(min)
    initial: 1
    min: 0
    max: 59
    step: 1
    icon: mdi:clock
 
# Services creation
shell_command:
    set_lamp_on: echo "1" > ~/hass/temp/lamp
    set_lamp_off: echo "0" > ~/hass/temp/lamp
    set_fan_on: echo "1" > ~/hass/temp/fan
    set_fan_off: echo "0" > ~/hass/temp/fan

group:
  System state:
    - binary_sensor.lamp
    - binary_sensor.fan
    - sensor.temperature
    - sensor.humidity
    - sensor.time 
  Override:
    - input_boolean.override
    - input_boolean.lamp_control
    - input_boolean.fan_control
  Lamp control:
    - sensor.time_lamp_on
    - input_slider.time_lamp_on_hour
    - input_slider.time_lamp_on_minute
    - sensor.time_lamp_off
    - input_slider.time_lamp_off_hour
    - input_slider.time_lamp_off_minute
  Fan control:
    - sensor.temperature_fan_threshold_value
    - input_slider.temperature_fan_threshold
    - input_slider.temperature_fan_hysteresis
    - sensor.humidity_fan_threshold_value
    - input_slider.humidity_fan_threshold
    - input_slider.humidity_fan_hysteresis

automation: !include_dir_merge_list automation

