# HA Startup fan control logic
- alias: Start fan upon HA startup by temperature and humidity
  trigger:
    platform: event
    event_type: homeassistant_start
  condition:
      condition: or
      conditions:
        - condition: template
          value_template: '{{ float(states.sensor.temperature.state) > float(states.sensor.temperature_fan_threshold.state) }}'
        - condition: template
          value_template: '{{ float(states.sensor.humidity.state) > float(states.sensor.humidity_fan_threshold.state) }}'
  action:
    - service: shell_command.set_fan_on
    - service: input_boolean.turn_on
      entity_id: input_boolean.fan_value

# Fan control logic
- alias: Start fan by temperature
  trigger:
    - platform: state
      entity_id: binary_sensor.trigger_temperature
      to: 'on'
      for:
          seconds: !env_var HA_TIME_HYSTERESIS_TEMPERATURE
  condition:
    - condition: state
      entity_id: input_boolean.override
      state: 'off'
  action: 
    - service: shell_command.set_fan_on
    - service: input_boolean.turn_on
      entity_id: input_boolean.fan_value

- alias: Start fan by humidity
  trigger:
    platform: state
    entity_id: binary_sensor.trigger_humidity
    to: 'on'
    for:
        seconds: !env_var HA_TIME_HYSTERESIS_HUMIDITY
  condition:
    - condition: state
      entity_id: input_boolean.override
      state: 'off'
  action: 
    - service: shell_command.set_fan_on
    - service: input_boolean.turn_on
      entity_id: input_boolean.fan_value

- alias: Stop fan by temperature
  trigger:
    platform: state
    entity_id: binary_sensor.trigger_temperature
    to: 'off'
    for:
        seconds: !env_var HA_TIME_HYSTERESIS_TEMPERATURE
  condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.override
          state: 'off'
        - condition: state
          entity_id: binary_sensor.trigger_humidity
          state: 'off' 
  action: 
    - service: shell_command.set_fan_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.fan_value

- alias: Stop fan by humidity
  trigger:
    platform: state
    entity_id: binary_sensor.trigger_humidity
    to: 'off'
    for:
        seconds: !env_var HA_TIME_HYSTERESIS_HUMIDITY
  condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.override
          state: 'off'
        - condition: state
          entity_id: binary_sensor.trigger_temperature
          state: 'off'
  action: 
    - service: shell_command.set_fan_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.fan_value

# Fan override
- alias: Fan on override
  trigger:
    platform: state
    entity_id: input_boolean.fan_control
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.override
      state: 'on'
  action: 
    - service: shell_command.set_fan_on
    - service: input_boolean.turn_on
      entity_id: input_boolean.fan_value

- alias: Fan off override
  trigger:
    platform: state
    entity_id: input_boolean.fan_control
    from: 'on'
    to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.override
      state: 'on'
  action: 
    - service: shell_command.set_fan_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.fan_value

- alias: Upon enable override set fan to current state ON
  trigger:
    platform: state
    entity_id: input_boolean.override
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.fan_value
      state: 'on'
  action: 
    - service: input_boolean.turn_on
      entity_id: input_boolean.fan_control

- alias: Upon enable override set fan to current state OFF
  trigger:
    platform: state
    entity_id: input_boolean.override
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.fan_value
      state: 'off'
  action: 
    - service: input_boolean.turn_off
      entity_id: input_boolean.fan_control

- alias: Upon disable override return fan to required state ON
  trigger:
    platform: state
    entity_id: input_boolean.override
    from: 'on'
    to: 'off'
  condition:
      condition: or
      conditions:
        - condition: template
          value_template: '{{ float(states.sensor.temperature.state) > float(states.sensor.temperature_fan_threshold.state) }}'
        - condition: template
          value_template: '{{ float(states.sensor.humidity.state) > float(states.sensor.humidity_fan_threshold.state) }}'
  action: 
    - service: shell_command.set_fan_on
    - service: input_boolean.turn_on
      entity_id: input_boolean.fan_value

- alias: Upon disable override return fan to required state OFF
  trigger:
    platform: state
    entity_id: input_boolean.override
    from: 'on'
    to: 'off'
  condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ float(states.sensor.temperature.state) < float(states.sensor.temperature_fan_threshold.state) }}'
        - condition: template
          value_template: '{{ float(states.sensor.humidity.state) < float(states.sensor.humidity_fan_threshold.state) }}'
  action: 
    - service: shell_command.set_fan_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.fan_value

